name: ARM Memory Reorder Test

on: [push]

jobs:
  test-arm:
    runs-on: ubuntu-24.04-arm
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Compile
      run: g++ -O2 -pthread reorder_arm.cpp -o store_buffering
    
    - name: Run test
      run: ./store_buffering
